-- Inserting values in PATIENT
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(19004439,"Sadie","Waylon",53,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(21309323,"Brooklyn","Zayn",23,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(13916314,"Collins","Isaiah",60,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(41624908,"Mason","Briggs",47,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(32609669,"Rylan","Kobe",44,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(23073565,"Rosalie","Tyler",54,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(54336725,"Nevaeh","Jax",67,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(96103090,"David","Holden",59,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(58297080,"Esme","Eduardo",54,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(77788796,"Kennedy","Russell",37,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(60393179,"Warren","Michael",38,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(57111009,"Samantha","Ari",39,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(43920085,"Danna","Niko",48,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(77091310,"George","Adriel",50,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(33672515,"Brady","Jay",21,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(20325175,"Harlow","Wade",25,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(89401734,"Manuel","Jasper",28,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(71818826,"Brianna","Ryker",48,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(33679449,"Ember","Luke",32,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(94426882,"Clayton","Kyrie",21,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(28978596,"Braxton","Khalil",35,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(25050824,"Hudson","George",49,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(95676246,"Chance","Rafael",47,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(55851635,"Ian","Matias",69,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(54377505,"Hadley","Jaxon",29,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(44602965,"Ariyah","Clayton",46,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(93757703,"Callum","Ezra",33,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(28675965,"Eliza","Nathan",65,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(57102397,"Natalia","Cayden",25,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(33483464,"Arthur","Alex",26,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(87299940,"Eliza","Benjamin",63,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69730623,"Maxwell","Ali",66,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(41017509,"Aaliyah","Derek",40,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(34744377,"Cody","Finley",36,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(72707945,"Cohen","Austin",41,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(82579475,"Miguel","Omar",59,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(56307006,"Trinity","Ali",52,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(81513689,"Delaney","Anderson",64,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(21497749,"Joanna","Preston",66,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(27586364,"Ryder","Joaquin",21,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(26448631,"Leo","Kairo",43,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69946964,"Emily","Zayn",63,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(44161982,"Blair","Victor",64,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(92060419,"Lucas","Angelo",47,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(60973700,"Alayah","Jordan",38,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(97071655,"Charles","Cameron",39,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(92431432,"Ayla","Callan",63,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(27371709,"Joshua","Caden",31,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(99349740,"Aaron","Arlo",43,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(46127712,"Wesley","Levi",23,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(21865831,"Jack","Cameron",35,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(75379766,"Elaina","Maverick",56,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(24294701,"Sawyer","Anthony",57,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(52055414,"Dakota","Dylan",64,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(59276965,"Ashton","Derek",61,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(81258698,"Adeline","Mark",22,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(14641920,"Thiago","Nicholas",42,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(89388971,"Thiago","Santiago",23,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(83090366,"Vivienne","Nico",51,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(55605274,"Brooklynn","Marcus",53,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(84384281,"Hannah","Stephen",44,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(28318246,"Nova","Elliot",48,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(73459859,"Jax","Ethan",32,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(29509925,"Hope","Colton",47,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(47030951,"Madeline","Timothy",56,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69717723,"Sophie","Tyler",52,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(52401067,"Jason","Archer",24,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(78675487,"Adriana","Everett",59,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(25191352,"Zion","Brian",66,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(67397047,"Eliza","Benjamin",36,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(51117722,"Evie","Chance",22,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(34472700,"Giovanni","Rylan",54,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(15576729,"Mia","Prince",62,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(36009157,"Raymond","Kameron",65,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(39942547,"Mckenna","Clayton",65,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(72262249,"Sawyer","Alexander",69,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(19959899,"Colin","Robert",57,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(73887485,"Joel","Caleb",60,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(33253322,"Rachel","Kaleb",64,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(33479664,"Juniper","Maddox",67,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(70451843,"Riley","Tucker",35,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(39166182,"Everly","Remy",45,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(98036479,"Vivienne","Tyler",50,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(80614422,"Violet","Elias",30,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(77087812,"Finn","Elias",66,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(44198466,"Khloe","River",53,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(59271279,"Kailani","Matthew",53,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(50696526,"Angelo","Wilder",42,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(63980276,"Bradley","Lincoln",22,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(25743572,"Tate","Kash",41,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(24270902,"Blair","Micah",44,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(98726654,"Jasper","Easton",33,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(41809652,"Roman","Alexander",56,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(51178505,"Liliana","Axel",55,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(42544023,"Kash","Zander",35,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(46304704,"Calvin","Carter",28,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(60225892,"Jaden","Abraham",22,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(43729055,"Juliana","Remington",31,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(74006980,"Charlotte","Cody",25,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(53401106,"Brayden","Simon",33,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(82810464,"Jaxson","Sullivan",58,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(27507799,"Avery","Aiden",31,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(89331614,"Ariyah","Cameron",65,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(65646177,"Teagan","Michael",27,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(82488482,"Mariana","Atlas",54,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(70311545,"Cyrus","Ricardo",33,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69154003,"Adalynn","Atlas",34,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(24201382,"Melissa","Graham",34,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69675967,"Mya","Manuel",42,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(32086752,"Joshua","Carter",64,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(46875031,"Madison","Paxton",66,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(62698968,"Muhammad","Daxton",48,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(88805396,"Paxton","Lucas",46,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(11286213,"Elias","Remington",49,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(27481825,"Payton","David",64,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(54123572,"Kayson","Gideon",24,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(81632705,"Rylan","Tristan",53,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(94554918,"Maggie","Bryson",38,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(71852686,"Kailani","Jesus",48,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(38399093,"Bradley","Roman",23,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(87847902,"Adonis","Josue",48,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(55018418,"Presley","Nathan",27,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(34057160,"Journee","Braxton",39,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69878789,"Bryson","Jose",52,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(74635521,"Theodore","Andre",40,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(98288542,"Jason","Vincent",44,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(72600878,"Melissa","John",26,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(44747025,"Faith","Jayce",60,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(67410054,"Ezequiel","Felix",44,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(48610038,"Kylie","Santiago",53,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(52370911,"Tyler","Rylan",68,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(50200479,"Leon","Sean",56,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(98238902,"Summer","Charles",36,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69166909,"Chloe","Charlie",69,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(23723976,"Kayson","Easton",24,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(22297515,"Mabel","Hudson",37,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(44734691,"Colt","Bryce",42,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(62862623,"Wren","Angel",60,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(25394992,"Freya","Wade",44,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(79460644,"Khalil","Walter",30,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(90837710,"Nevaeh","Henry",59,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(52968514,"Milani","Manuel",54,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(41675180,"Arlo","Antonio",66,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(30764021,"Mariah","Theodore",43,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(86367688,"Nora","Wilder",49,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(76523801,"Brynn","Dallas",68,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(79230072,"Russell","Ivan",27,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(17374665,"Kehlani","Colt",28,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69861899,"Phoenix","Joel",41,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(93818469,"Gabriel","Prince",69,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(16272343,"Marley","Maverick",66,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(10124109,"Benjamin","Ismael",53,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(27442569,"Serenity","Cooper",21,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(91522367,"Kalani","Rowan",45,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(29651591,"Ada","Dean",67,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(33610275,"Spencer","Kingston",21,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(26308672,"Adaline","Kash",58,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(41987160,"Steven","Cooper",67,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(39877764,"Reign","Thiago",56,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(36788499,"Mariah","Vincent",35,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(64172205,"Rylee","Tate",29,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(19816719,"Morgan","Kobe",38,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(59241499,"Corbin","Brayden",47,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(69194286,"Ellis","Colson",38,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(42007809,"Samuel","Khalil",59,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(35919529,"Eliza","Atlas",60,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(61523317,"Axel","Briggs",52,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(21200210,"Rowan","Dakota",52,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(90017467,"Ayla","Matias",49,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(13446633,"Ana","Gael",49,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(26262724,"Mariah","Tanner",42,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(11516657,"Everlee","Lawson",39,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(49630064,"Noelle","Myles",57,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(91296649,"Layla","Henry",57,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(62198917,"Dante","Rylan",46,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(52395691,"Griffin","Xander",33,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(44582755,"Myles","Brody",53,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(11562713,"Omar","Matteo",55,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(33523135,"Gael","Legend",62,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(60122557,"Adalyn","Killian",29,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(44162156,"Ian","Noah",68,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(34001822,"Michael","Aaron",45,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(49448815,"Orion","Ali",51,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(60136107,"Paxton","Corbin",26,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(57173913,"Adonis","Andrew",36,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(77311661,"Caroline","Jack",39,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(24755038,"John","Holden",45,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(27826804,"Ari","Simon",50,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(25082917,"Isaac","Amari",21,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(68013203,"Callan","Thomas",51,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(57679739,"Molly","Luka",66,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(47784981,"Madison","Kenneth",57,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(72390822,"Aubrey","Bennett",64,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(59495606,"Sydney","Simon",40,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(89143611,"Paige","Barrett",39,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(38330503,"Annabelle","Silas",22,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(62774737,"Robert","Rafael",22,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(49169062,"Sadie","Walter",21,"F");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(83699740,"Judah","Cody",53,"M");
INSERT INTO PATIENT(ID,first_name,last_name,age,sex) VALUES(10764494,"Ana","Max",30,"F");

INSERT INTO DISEASE VALUES("Alzheimer","NS");
INSERT INTO DISEASE VALUES("Huntington's Disease","NS");
INSERT INTO DISEASE VALUES("ADHD","NS");
INSERT INTO DISEASE VALUES("Parkinson","NS");
INSERT INTO DISEASE VALUES("Ataxia","NS");
INSERT INTO DISEASE VALUES("Niemann-Pick","NS");
INSERT INTO DISEASE VALUES("Angelman's Syndrome","NS");

-- inserting genes
INSERT INTO GENE VALUES("PSEN1","presenilin 1","14","73136418-73223691","forward strand","Alzheimer");
INSERT INTO GENE VALUES("PSEN2","presenilin 2","1","226870184-226927726","forward strand","Alzheimer");
INSERT INTO GENE VALUES("APP","amyloid beta precursor protein","21","25880550-26171128","reverse strand","Alzheimer");
INSERT INTO GENE VALUES("HTT","huntingtin","4","3041363-3243957","forward strand","Huntington's Disease");
INSERT INTO GENE VALUES("FOXN3","forkhead box N3","14","89124871-89619149","reverse strand","ADHD");
INSERT INTO GENE VALUES("LMOD2","leiomodin 2","7","123655866-123664290","forward strand","ADHD");
INSERT INTO GENE VALUES("SNCA","synuclein alpha","4","89700345-89838315","reverse strand","Parkinson");
INSERT INTO GENE VALUES("NDUFAF6","NADH:ubiquinone oxidoreductase complex assembly factor 6","8","94895533-95116455","forward strand","Ataxia");
INSERT INTO GENE VALUES("NPC1","NPC intracellular cholesterol transporter 1","18","23506184-23586506","reverse strand","Niemann-Pick");
INSERT INTO GENE VALUES("UBE3A","ubiquitin protein ligase E3A","15","25333728-25439051","reverse strand","Angelman's Syndrome");
INSERT INTO GENE VALUES("SNHG14","small nucleolar RNA host gene 14","15","24978583-25420336","forward strand","Angelman's Syndrome");


-- inserting into variant
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(220,11177,NULL,"Retained intron ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,812,NULL,"Retained intron ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(244,7005,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,24124,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,17832,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(224,15109,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(270,13199,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(282,11322,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(269,11055,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(231,9815,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(323,9720,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(324,9720,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(340,9585,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(309,9319,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,8842,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(313,8814,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(255,8811,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(338,8738,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(227,8498,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(332,8415,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(254,8307,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(333,8250,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(315,8232,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(304,8201,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(275,8095,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(235,7914,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(276,7908,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(274,7757,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(232,7749,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(228,7723,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(278,7640,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(230,7549,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(280,7537,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(272,7504,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(311,7500,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(312,7423,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(249,7374,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(287,7339,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(268,7338,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,7315,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(242,7238,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(283,7146,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(297,7140,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(277,6939,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(300,6860,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(239,6860,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(301,6823,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(318,6757,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(314,6701,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(279,6659,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(246,6631,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(298,6540,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(295,6507,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(281,6463,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(248,6462,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(325,6429,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(329,6336,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(331,6331,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,6087,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(334,5995,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(285,5976,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(257,5911,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(262,5819,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(330,5786,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(288,5563,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(296,5472,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(319,5387,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(299,5370,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(293,5354,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(322,5334,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(291,5278,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(251,5196,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(294,5175,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(335,5151,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(303,5055,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,5027,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(273,4873,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(229,4751,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(310,4682,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(317,4660,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(263,4554,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(326,4483,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(316,4315,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(266,4279,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(292,4267,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(236,4259,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(284,4255,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(328,4199,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(306,4149,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(327,4147,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(226,4080,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(245,4035,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(320,3993,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(321,3788,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(225,3733,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(290,3415,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(260,3192,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(233,3191,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(234,3186,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,3166,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(264,3133,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(238,3066,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(302,3060,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(342,3048,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(243,2838,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(241,2837,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(256,2641,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(305,2566,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(267,2541,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(250,2470,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(289,2256,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(265,2150,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(259,2094,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(247,1945,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(341,1869,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(253,1791,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(223,1747,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(237,1738,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(336,1707,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(286,1648,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(337,1530,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(221,1512,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(252,1220,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(271,1179,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(219,1168,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,1108,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,1064,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(339,1008,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,916,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(261,905,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(308,"831 No protein ","lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(240,690,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,626,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,610,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,608,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(307,582,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(258,557,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,552,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,550,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(218,513,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(222,511,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,470,NULL,"lncRNA ","SNHG14");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(226,8728,872  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(221,9352,813  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(225,9131,852  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,8939,852  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(224,8742,852  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(223,8725,872  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(222,5726,51  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(228,5274,875  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,5075,852  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(227,5025,852  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,4968,765  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,3176,852  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,2986,852  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(231,2598,813  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,1112,49  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(219,889,148  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,779,49  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,706,187  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,654,14  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,571,189  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,445,143  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,436,77  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,424,39  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,394,8  ,"Protein coding ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(233,1536,NULL,"Protein coding CDS not defined ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(220,789,NULL,"Protein coding CDS not defined ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,733,NULL,"Protein coding CDS not defined ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,474,NULL,"Protein coding CDS not defined ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(232,5196,NULL,"Retained intron ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(229,3371,NULL,"Retained intron ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(230,2672,NULL,"Retained intron ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(218,1873,NULL,"Retained intron ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,772,NULL,"Retained intron ","UBE3A");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,4760,1278  ,"Protein coding","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,3171,971  ,"Protein coding","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,1607,42  ,"Protein coding","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,890,179  ,"Protein coding","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,755,59  ,"Protein coding","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,571,175  ,"Protein coding","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,2790,NULL,"Protein coding CDS not defined","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,590,NULL,"Protein coding CDS not defined","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,2000,NULL,"Retained intron","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,809,NULL,"Retained intron","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,574,NULL,"Retained intron","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,561,NULL,"Retained intron","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,431,NULL,"Retained intron","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,410,NULL,"Retained intron","NPC1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,1795,333  ,"Protein coding","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,2549,241  ,"Protein coding","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(231,1879,241  ,"Protein coding","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,1869,241  ,"Protein coding","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(219,949,133  ,"Protein coding","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,816,95  ,"Protein coding","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(222,2339,48  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,1474,142  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,1373,121  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,1196,97  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,1147,103  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,946,82  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,845,93  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(218,796,121  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,582,102  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,561,58  ,"Nonsense mediated decay","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(226,3711,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(223,3449,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(224,2295,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(221,2055,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,1853,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(228,1655,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(229,1568,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(225,1141,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(227,1076,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(230,998,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,732,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,712,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(220,709,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(232,561,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(233,546,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,453,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,449,NULL,"Protein coding CDS not defined","NDUFAF6");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,3177,140  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,3167,126  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,3131,140  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,3127,112  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,3041,140  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,3022,126  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,2183,151  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,2139,159  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,1420,140  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,1096,112  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,905,140  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,731,115  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,570,140  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,411,126  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,387,66  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,297,98  ,"Protein coding","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,3193,NULL,"Protein coding CDS not defined","SNCA");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,13472,3142  ,"Protein coding ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(223,14033,3086  ,"Protein coding ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(222,13943,3056  ,"Protein coding ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,429,112  ,"Protein coding ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,289,97  ,"Protein coding ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(221,13984,2191  ,"Nonsense mediated decay ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(219,13834,2880  ,"Nonsense mediated decay ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,503,75  ,"Nonsense mediated decay ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(218,390,75  ,"Nonsense mediated decay ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,1324,NULL,"Protein coding CDS not defined ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,587,NULL,"Protein coding CDS not defined ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,432,NULL,"Protein coding CDS not defined ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,331,NULL,"Protein coding CDS not defined ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,14438,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(220,7184,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,781,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,723,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,611,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,401,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,386,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,380,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,373,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,259,NULL,"Retained intron ","HTT");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,8021,468  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,7832,490  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,2542,490  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(219,2421,468  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,1595,468  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,851,208  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,555,185  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,513,79  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,505,93  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,467,111  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,366,122  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,337,54  ,"Protein coding ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,450,91  ,"Nonsense mediated decay ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(218,398,76  ,"Nonsense mediated decay ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,648,NULL,"Protein coding CDS not defined ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,625,NULL,"Protein coding CDS not defined ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,388,NULL,"Protein coding CDS not defined ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,340,NULL,"Protein coding CDS not defined ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,228,NULL,"Protein coding CDS not defined ","FOXN3");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,3583,770  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,3543,751  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,3355,695  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,3294,660  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,3167,639  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,2846,746  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,2517,714  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,2366,752  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,1846,485  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,541,181  ,"Protein coding ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,1309,NULL,"Protein coding CDS not defined ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,619,NULL,"Protein coding CDS not defined ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,582,NULL,"Protein coding CDS not defined ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,374,NULL,"Protein coding CDS not defined ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,361,NULL,"Protein coding CDS not defined ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,816,NULL,"Retained intron ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,667,NULL,"Retained intron ","APP");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,2249,448  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(224,5158,471  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(236,3703,448  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,3116,448  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,2465,448  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(219,2413,527  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(229,2193,415  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(221,2144,448  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,2117,448  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,1947,447  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(226,1935,303  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,1163,304  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,782,144  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,627,129  ,"Protein coding","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(234,4008,366  ,"Nonsense mediated decay ","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(237,3772,448  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,3763,399  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(235,3480,263  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(228,2990,448  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(230,2984,367  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(232,2713,54  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,2690,54  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(223,2613,54  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,2566,321  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(231,2461,263  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(218,2369,165  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(227,2026,53  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,1822,321  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(233,1717,367  ,"Nonsense mediated decay","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,2966,NULL,"Protein coding CDS not defined","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,1467,NULL,"Protein coding CDS not defined","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,566,NULL,"Protein coding CDS not defined","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(225,4109,NULL,"Retained intron","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(222,3584,NULL,"Retained intron","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,2492,NULL,"Retained intron","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(220,2415,NULL,"Retained intron","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,730,NULL,"Retained intron","PSEN2");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(201,6018,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(265,6396,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(233,6116,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(207,6099,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(237,6091,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(242,6089,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(232,6076,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(262,6075,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(209,6064,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(218,6062,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(259,6056,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(256,6034,476  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(249,6032,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(257,6014,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(260,6013,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(253,5975,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(258,5961,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(231,5957,467  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(220,5953,427  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(243,5935,434  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(229,5911,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(248,5907,384  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(235,5874,405  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(288,5791,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(285,5789,384  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(287,5654,430  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(204,3046,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(268,3019,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(202,2776,463  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(203,1249,184  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(222,1230,409  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(279,1100,180  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(211,754,155  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(224,699,109  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(217,574,63  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(221,571,135  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(219,555,62  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(216,550,92  ,"Protein coding ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(264,6507,215  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(230,6413,37  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(225,6388,379  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(245,6230,37  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(236,6189,61  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(240,6183,61  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(241,6163,183  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(244,6145,57  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(251,6129,187  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(223,6110,57  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(238,6101,408  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(252,6099,103  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(250,6093,48  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(247,6088,408  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(239,6074,116  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(254,6032,120  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(246,5985,341  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(255,5939,163  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(284,5857,378  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(212,1752,374  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(208,1254,378  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(278,1210,61  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(214,924,61  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(206,877,57  ,"Nonsense mediated decay ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(266,6198,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(275,2215,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(276,2203,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(270,1728,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(277,1484,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(283,1417,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(272,1370,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(273,1359,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(261,1289,NULL,"Protein coding CDS not defined ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(226,11342,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(269,7511,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(271,6629,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(210,6545,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(215,6221,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(228,5149,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(205,4062,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(274,2226,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(286,2077,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(234,1994,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(280,1841,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(263,1621,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(282,1620,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(281,1584,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(227,1426,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(267,1152,NULL,"Retained intron ","PSEN1");
INSERT INTO VARIANT(variant_no,size,protein_size,biotype,gene) VALUES(213,876,NULL,"Retained intron ","PSEN1");

-- adding compounds

INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL601773",611.74,"C35H41N5O5","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL3039540",145912.34,"C6472H10028N1740O2014S46","Antibody");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL85",410.49,"C23H27FN4O2","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL429724",145087.7,"C6452H10038N1708O2013S42","Antibody");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL4297384",439.55,"C21H25N7O2S","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL1364",169.18,"C8H11NO3","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL806",276.21,"C11H11F3N2O3","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL126",337.35,"C16H20FN3O4","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL317052",390.36,"C15H18N8O5","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL2105617",326.44,"C20H26N2O2","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL4802144",194.234,"C10H14N2O2","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL1029",219.278,"C10H21NO4","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL3545232",294.4,"C19H22N2O","Small Molecule");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL4524066",3753.28,"C172H267N43O51","Protein");
INSERT INTO COMPOUND(ID,weight,molecular_formula,type) VALUES("CHEMBL127071",192.26,"C11H16N2O","Small Molecule");

-- adding drugs

INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Dihydroergocristine",0,NULL,"CHEMBL601773");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Aducanumab",4,"Protein Based Therapies","CHEMBL3039540");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Risperidone",4,NULL,"CHEMBL85");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Donanemab",3,"Protein Based Therapies","CHEMBL429724");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("GSK-356278",1,NULL,"CHEMBL4297384");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Pyridoxine",4,NULL,"CHEMBL1364");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Flutamide",4,NULL,"CHEMBL806");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Linezolid",4,NULL,"CHEMBL126");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Regadenoson",4,NULL,"CHEMBL317052");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Ajmaline",3,NULL,"CHEMBL2105617");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("NNZ-2591",1,NULL,"CHEMBL4802144");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Miglustat",4,NULL,"CHEMBL1029");
INSERT INTO DRUG(generic_name,phase,classification,molecule)  VALUES("Pozanicline",2,NULL,"CHEMBL127071");

-- adding brand names

INSERT INTO BRAND_NAME(drug,name) VALUES("Aducanumab","Aduhelm");
INSERT INTO BRAND_NAME(drug,name) VALUES("Risperidone","Perseris");
INSERT INTO BRAND_NAME(drug,name) VALUES("Risperidone","Risperdal");
INSERT INTO BRAND_NAME(drug,name) VALUES("Flutamide","Eulexin");
INSERT INTO BRAND_NAME(drug,name) VALUES("Regadenoson","Lexiscan");
INSERT INTO BRAND_NAME(drug,name) VALUES("Miglustat","Zavesca");
INSERT INTO BRAND_NAME(drug,name) VALUES("Linezolid","Zyvoxam");


-- inserting records

INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date,effective) VALUES(32086752,"Donanemab","Angelman's Syndrome",'2019-08-04');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(72707945,"Linezolid","Parkinson",'2008-09-27');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(89401734,"Dihydroergocristine","Angelman's Syndrome",'2018-10-11');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(69675967,"Flutamide","Parkinson",'2012-08-25');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(69946964,"Pozanicline","Huntington's Disease",'2017-03-07');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(44198466,"GSK356278","Alzheimer",'2018-05-17');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(19959899,"Flutamide","Parkinson",'2000-02-03');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(25743572,"Ajmaline","Ataxia",'2002-11-27');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(11516657,"Regadenoson","ADHD",'2012-08-09');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(95676246,"NNZ2591","Ataxia",'2011-04-10');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(97071655,"Regadenoson","Alzheimer",'2005-03-10');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(70311545,"Risperidone","Huntington's Disease",'2021-10-11');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(11286213,"NNZ2591","Huntington's Disease",'2008-07-12');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(33479664,"Pyridoxine","Niemann-Pick",'2009-02-04');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(33679449,"Pyridoxine","Parkinson",'2006-04-28');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(55851635,"Ajmaline","Parkinson",'2022-11-18');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(82488482,"Pozanicline","Parkinson",'2015-12-19');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(43920085,"Flutamide","Alzheimer",'2007-08-23');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(83699740,"Donanemab","Alzheimer",'2012-05-03');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(73887485,"Risperidone","ADHD",'2022-01-23');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(24270902,"Donanemab","Alzheimer",'2004-04-11');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(92431432,"Pyridoxine","Ataxia",'2009-10-20');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(44582755,"Flutamide","ADHD",'2001-12-14');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(82579475,"Linezolid","Ataxia",'2014-12-15');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(34057160,"Donanemab","ADHD",'2013-08-28');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(77091310,"Flutamide","Angelman's Syndrome",'2017-08-27');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(57173913,"NNZ2591","Angelman's Syndrome",'2012-06-10');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(64172205,"Pyridoxine","Ataxia",'2003-03-10');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(82810464,"Donanemab","ADHD",'2021-05-21');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(92060419,"Pyridoxine","Huntington's Disease",'2017-08-17');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(47030951,"Linezolid","ADHD",'2002-02-11');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(67410054,"Ajmaline","Angelman's Syndrome",'2002-01-13');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(75379766,"Pozanicline","Parkinson",'2019-05-05');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(51117722,"Flutamide","Alzheimer",'2008-09-16');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(33483464,"Aducanumab","Angelman's Syndrome",'2016-10-19');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(50696526,"Donanemab","Alzheimer",'2013-04-20');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(36788499,"Regadenoson","Parkinson",'2007-06-16');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(22297515,"Dihydroergocristine","Parkinson",'2012-11-02');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(26262724,"NNZ2591","Parkinson",'2018-09-22');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(21200210,"Pozanicline","Angelman's Syndrome",'2010-07-19');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(91296649,"Linezolid","Parkinson",'2008-07-17');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(89331614,"Ajmaline","Ataxia",'2022-12-27');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(67397047,"Flutamide","Niemann-Pick",'2000-03-04');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(94554918,"GSK356278","Angelman's Syndrome",'2014-12-28');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(89143611,"GSK356278","Angelman's Syndrome",'2001-09-11');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(49448815,"Aducanumab","ADHD",'2006-03-14');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(39166182,"Pozanicline","ADHD",'2020-10-14');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(13446633,"Flutamide","Parkinson",'2000-06-25');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(72262249,"Regadenoson","Alzheimer",'2010-03-28');
INSERT INTO RECORD(patient_id,drug_name,disease_name,test_date) VALUES(41017509,"Ajmaline","Alzheimer",'2014-03-22');